# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussiontree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussiontree.DiscussionNode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='credibility_factor',
            field=models.IntegerField(default=1),
        ),
    ]
